title: <strong>Noite de Processing @ Recife</strong>

site_name: noite_processing_recife

# Name of your blog (this will show up at the top of your page and in the RSS feed)
name: noite_processing_recife

# Short description (goes below the title; it will also be used in the RSS feed)
# description: arte e programação

# Your name, as you want it to appear underneath each post and in the footer
author: noite_processing_recife

# Your email if you want it to be linked on the contact page
# author_email:

# The URL of your actual domain. This will be used to make absolute links in the RSS feed.
url: http://arteprog.space

# logo: /assets/logo.png

# google_analytics:
